# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */24 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["output"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: general 
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: bio.svg
          optimize: svg
          experimental_features: --optimize-svg
          user: lamisgosu11
          template: terminal
          base: header
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: Jupyter Notebook, tex
          plugin_languages_limit: 4         
          config_order: base.header, introduction, isocalendar, languages
          config_timezone: Asia/Saigon
          output_action: commit
          commiter_branch: metrics-renders
          commiter_message: "Daily update for metrics"
          
